### PR TITLE
Support to Symfony 7.1

### PR DESCRIPTION
**Pull request by fluchi**
Changed constraints to allow upgrade to Symfony 7.1

### CODE REVIEW

**Comment by Jean-Gian** [comment]
Is there anyone that can approve and merge?
This is blocking symfony 7 upgrades

Thanks!

**Comment by asprega** [comment]
I'm sorry, I was away and just noticed this. I will prepare a release soon

**Comment by asprega** [comment]
Included in release 2.1.0. Thanks!

**Comment by Jean-Gian** [comment]
Thanks a lot @asprega and @fluchi

**Pull request merged**
